import type {
  ExperienceGenome,
  ExperienceTrace,
  ProjectGenome,
} from "@/lib/genome/schema";

export const demoTrace: ExperienceTrace = {
  id: "trace-drift-lab-v1",
  referenceId: "ref-drift-lab",
  sourceName: "Experience Compiler Drift Lab",
  sourceUrl: "https://experience-genome.vercel.app/fixture?representation=static",
  sourceMode: "controlled-fixture",
  collectorId: "collector-creation-in-progress",
  snapshotId: "fixture-preview",
  capturedAt: "2026-08-23T16:45:00.000Z",
  states: [
    {
      id: "S01",
      sequence: 1,
      label: "INSCRIPTION",
      elapsedMs: 0,
      url: "https://experience-genome.vercel.app/fixture?representation=static",
      heading: "A world can be read before it is understood.",
      textExcerpt: "The semantic signal is present, but the experience is dormant.",
      signals: [
        { key: "semantic_reveal", value: "hidden", provenance: "dom" },
        { key: "world_depth", value: "0", provenance: "visual" },
        { key: "ambient_light", value: "82%", provenance: "visual" },
      ],
    },
    {
      id: "S02",
      sequence: 2,
      label: "APPROACH",
      elapsedMs: 1200,
      url: "https://experience-genome.vercel.app/fixture?representation=static",
      heading: "The world approaches first.",
      textExcerpt: "Spatial movement establishes scale before language arrives.",
      signals: [
        { key: "semantic_reveal", value: "hidden", provenance: "dom" },
        { key: "world_depth", value: "-4.2", provenance: "visual" },
        { key: "ambient_light", value: "44%", provenance: "visual" },
      ],
    },
    {
      id: "S03",
      sequence: 3,
      label: "SEMANTIC REVEAL",
      elapsedMs: 1440,
      url: "https://experience-genome.vercel.app/fixture?representation=static",
      heading: "Meaning arrives after scale.",
      textExcerpt: "Only after the spatial event settles does the label become readable.",
      signals: [
        { key: "semantic_reveal", value: "visible", provenance: "dom" },
        { key: "world_depth", value: "-4.2", provenance: "visual" },
        { key: "ambient_light", value: "44%", provenance: "visual" },
      ],
    },
  ],
  actions: [
    {
      id: "A01",
      fromState: "S01",
      toState: "S02",
      type: "scroll",
      label: "scroll +410px",
      durationMs: 1200,
      actor: "fixture",
    },
    {
      id: "A02",
      fromState: "S02",
      toState: "S03",
      type: "wait",
      label: "wait 240ms",
      durationMs: 240,
      actor: "fixture",
    },
  ],
  deltas: [
    {
      id: "D01",
      fromState: "S01",
      toState: "S02",
      summary: "Depth advances and light falls while language remains withheld.",
      kind: "observed-after-action",
      changedSignals: ["world_depth", "ambient_light"],
    },
    {
      id: "D02",
      fromState: "S02",
      toState: "S03",
      summary: "The semantic label appears only after the spatial approach settles.",
      kind: "mechanism-observed",
      changedSignals: ["semantic_reveal"],
    },
  ],
};

export const demoGenome: ExperienceGenome = {
  id: "genome-drift-lab",
  referenceId: "ref-drift-lab",
  name: "Arrival Before Meaning",
  claims: [
    {
      id: "C01",
      referenceId: "ref-drift-lab",
      dimension: "motion",
      statement: "Spatial arrival precedes semantic reveal.",
      interpretation: "The visual event establishes scale before asking the user to read.",
      epistemicBasis: "observed",
      humanJudgment: "preferred",
      humanNote: "Keep the heavy, patient feeling of the reveal.",
      evidenceRefs: ["S01", "A01", "S02", "A02", "S03", "D01", "D02"],
    },
    {
      id: "C02",
      referenceId: "ref-drift-lab",
      dimension: "light",
      statement: "Ambient light contracts during approach.",
      interpretation: "Reduced peripheral light may focus attention on the arriving object.",
      epistemicBasis: "inferred",
      humanJudgment: "preferred",
      humanNote: "I like that it feels focused without becoming flashy.",
      evidenceRefs: ["S01", "S02", "D01"],
    },
    {
      id: "C03",
      referenceId: "ref-drift-lab",
      dimension: "layout",
      statement: "Reserve negative space around the primary intelligence object.",
      epistemicBasis: "user-specified",
      humanJudgment: "preferred",
      humanNote: "Do not bury the focal object in dashboard chrome.",
      evidenceRefs: [],
    },
    {
      id: "C04",
      referenceId: "ref-drift-lab",
      dimension: "mechanism",
      statement: "Audio response could not be established from the captured evidence.",
      epistemicBasis: "unresolved",
      humanJudgment: "unreviewed",
      evidenceRefs: ["S01", "S02", "S03"],
    },
  ],
  coverage: [
    {
      dimension: "Form",
      status: "grounded",
      reason: "DOM structure and viewport imagery agree.",
      claimRefs: ["C03"],
    },
    {
      dimension: "Macro motion",
      status: "grounded",
      reason: "Three ordered states retain the triggering actions.",
      claimRefs: ["C01"],
    },
    {
      dimension: "Lighting intent",
      status: "partial",
      reason: "The visual change is observed; authorial intent is inferred.",
      claimRefs: ["C02"],
    },
    {
      dimension: "Pointer physics",
      status: "partial",
      reason: "No repeated pointer trajectory was captured.",
      claimRefs: [],
    },
    {
      dimension: "Audio response",
      status: "unresolved",
      reason: "No reliable audio evidence was collected.",
      claimRefs: ["C04"],
    },
  ],
};

export const demoProjectGenome: ProjectGenome = {
  id: "project-genome-01",
  title: "Orbital Archive",
  brief: "A calm intelligence workspace that feels ancient, precise, and alive.",
  desiredAffect: ["anticipation", "weight", "lucid wonder"],
  generatedAt: "2026-08-23T16:47:00.000Z",
  model: {
    provider: "openrouter",
    id: "stealth/ox-alpha",
    promptVersion: "genome-synthesis-v1",
  },
  rules: [
    {
      id: "R01",
      title: "Arrival before language",
      rule: "Let the primary spatial event settle before revealing its semantic label.",
      transformation: "inherited",
      sourceClaimRefs: ["C01"],
      rationale: "Preserves the selected feeling of scale and anticipation.",
      implementationDirective: "Delay headline opacity until the hero object's approach animation completes.",
      antiCopyConstraint: "Do not reuse source geometry, timing values, copy, or camera path.",
    },
    {
      id: "R02",
      title: "Focused contraction",
      rule: "Reduce peripheral luminance only during high-importance spatial transitions.",
      transformation: "mutated",
      sourceClaimRefs: ["C02"],
      rationale: "Keeps the focus mechanism but limits it to rare narrative beats.",
      implementationDirective: "Animate ambient intensity down during the portal transition, then restore it gradually.",
      antiCopyConstraint: "Derive a new palette and easing curve from the project brief.",
    },
    {
      id: "R03",
      title: "No glass-card field",
      rule: "Reject dense fields of translucent cards around the focal object.",
      transformation: "rejected",
      sourceClaimRefs: ["C03"],
      rationale: "Human judgment explicitly prioritizes negative space.",
      implementationDirective: "Use one evidence panel at a time and let the world remain visible.",
      antiCopyConstraint: "Do not reproduce another product's panel grid or chrome hierarchy.",
    },
    {
      id: "R04",
      title: "Orbital capture",
      rule: "Secondary evidence converges as orbiting fragments, then resolves into labels only after attachment.",
      transformation: "invented",
      sourceClaimRefs: [],
      rationale: "Combines the brief's archival metaphor with selected temporal restraint.",
      implementationDirective: "Animate evidence fragments along distinct arcs into a stable rule node.",
      antiCopyConstraint: "Use original trajectories, silhouettes, vocabulary, and material language.",
    },
  ],
};

export const demoTraces = [demoTrace];
export const demoGenomes = [demoGenome];

